### ISSUE TITLE
Bugs when using --resume in text2im.py

### ISSUE THREAD

**Issue by Z-MU-Z** [yoctta/XPaste#3]
if args.resume:
        old=os.listdir(PATH)
        cls_names=[j['name'] for j in target_class]
        for i in cls_names:
            try:
                _=cv2.imread(os.path.join(PATH,f"{i}_{args.samples-1}.png"))
                cls_names.remove(i)
                print(f"skipping {i}")
            except:

"for i in cls_names" and "cls_names.remove(i)" will cause conflicts and incorrectly skipping some classes

**Comment by yoctta** [comment]
Thank you. Fixed it by "for i in old:"

**Comment by Z-MU-Z** [comment]
Hello! Recently I discovered other bugs that hinder the normal use of the --resume function:
python
# =cv2.imread(os.path.join(PATH,f"{i}{args.samples-1}.png"))
_=cv2.imread(os.path.join(PATH,f"{i}/00{args.samples-1}.png"))
The path name here is wrong. Additionally, since json cannot resume, I still need to write a dedicated function to calculate the clip score.
