### ISSUE TITLE
Error while training base model: RuntimeError: Expected !nested_tensorlist[0].empty() to be true, but got false.

### ISSUE THREAD

**Issue by Ab-34** [yoctta/XPaste#7]
Hi @yoctta , thank you for your code!

I was running lvis data on the base model `(configs/Base-C2_L_R5021k_640b64_4x/yaml)` and I run into this error: (I have not made any changes to the repo or the config file)

![image](https://github.com/yoctta/XPaste/assets/55902724/2a82d431-ffa3-4190-ab2a-baf7ba699b54)

Could you please let me know how to fix it?
Thank you!

**Comment by Ab-34** [comment]
I solved it by downgrading the pytorch version to 2.0.1+cu118.

Leaving it here incase someone else encounters the same issue.

**Comment by hhBonnie** [comment]
Hello, I also encountered the same problem as you, and then lowered the pytorch version, I would like to ask about the specific configuration of your environment, such as the numpy version, etc @Ab-34 .Looking forward to your reply.
